// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {main} from '../models';

export function CreateEmbedding(arg1:context.Context,arg2:string):Promise<Array<number>>;

export function ExtractDocuments(arg1:main.FileSystemNode):Promise<Array<main.Document>>;

export function GenerateAnswer(arg1:context.Context,arg2:string,arg3:Array<string>):Promise<string>;

export function GetStats():Promise<Record<string, any>>;

export function IndexDocuments(arg1:Array<main.Document>):Promise<void>;

export function Query(arg1:context.Context,arg2:string,arg3:number):Promise<string>;

export function SearchDocuments(arg1:context.Context,arg2:string,arg3:number):Promise<Array<main.SearchResult>>;

export function SimpleQuery(arg1:string):Promise<string>;
